// Generates the Tailwind v4 theme from tokens/tokens.json (the single source of truth).
//   src/styles/tokens.css            @theme static … + [data-theme="ink"] overrides  (the app)
//   src/styles/tokens.reference.css  @theme reference …                             (the Design System bundle,
//                                     whose page supplies colour/radius/shadow/font values; text sizes are static)
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'tokens/tokens.json'), 'utf8'));

export function buildCss(t) {
  const themes = t.color.themes.map((x) => x.id);
  const [first, ...rest] = themes;
  const valueIn = (tok, theme) => (typeof tok.value === 'string' ? tok.value : tok.value[theme] ?? tok.value[first]);
  const px = (v) => (typeof v === 'number' ? `${v}px` : v);

  const base = [];
  const text = [];
  for (const c of t.color.tokens) base.push(`  --${c.name}: ${valueIn(c, first)};`);
  for (const [key, stack] of Object.entries(t.type.families)) base.push(`  --font-${key}: ${stack};`);
  for (const g of t.type.groups) {
    for (const s of g.styles) {
      text.push(`  --text-${s.name}: ${px(s.fontSize)};`);
      if (s.lineHeight !== undefined) text.push(`  --text-${s.name}--line-height: ${s.lineHeight};`);
      if (s.letterSpacing !== undefined) text.push(`  --text-${s.name}--letter-spacing: ${s.letterSpacing};`);
      if (s.fontWeight !== undefined) text.push(`  --text-${s.name}--font-weight: ${s.fontWeight};`);
    }
  }
  for (const r of t.radius.tokens) base.push(`  --${r.name}: ${px(r.value)};`);
  for (const s of t.shadow?.tokens ?? []) base.push(`  --${s.name}: ${valueIn(s, first)};`);

  const overrides = rest.map((theme) => {
    const lines = [];
    for (const c of t.color.tokens) {
      if (typeof c.value === 'object' && c.value[theme] && c.value[theme] !== c.value[first]) lines.push(`  --${c.name}: ${c.value[theme]};`);
    }
    for (const s of t.shadow?.tokens ?? []) {
      if (typeof s.value === 'object' && s.value[theme]) lines.push(`  --${s.name}: ${s.value[theme]};`);
    }
    const scheme = theme === 'ink' ? '\n  color-scheme: dark;' : '';
    return `[data-theme="${theme}"] {\n${lines.join('\n')}${scheme}\n}`;
  });

  // Further families (layout, …) are plain CSS custom properties, not Tailwind theme namespaces.
  const known = new Set(['name', 'version', 'meta', 'color', 'type', 'spacing', 'radius', 'shadow']);
  const plain = Object.entries(t).filter(([k, v]) => !known.has(k) && v && Array.isArray(v.tokens))
    .flatMap(([, v]) => v.tokens.map((tok) => `  --${tok.name}: ${tok.value};`));
  const rootBlock = plain.length ? `\n:root {\n${plain.join('\n')}\n}\n` : '';
  const header = '/* Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit by hand. */\n';
  const reset = '  --color-*: initial;\n  --font-*: initial;\n  --text-*: initial;\n  --radius-*: initial;\n  --shadow-*: initial;\n';
  const app = `${header}@theme static {\n${reset}${base.join('\n')}\n${text.join('\n')}\n}\n${rootBlock}\n${overrides.join('\n\n')}\n`;
  // The Design System page compiles colours, shadows, radii and --font-* into its own tokens.css, but
  // type styles become .<style> classes there, not --text-* variables, so the bundle carries those itself.
  const reference = `${header}@theme reference {\n${reset}${base.join('\n')}\n}\n\n@theme static {\n${text.join('\n')}\n}\n`;
  return { app, reference };
}

const { app, reference } = buildCss(tokens);
mkdirSync(resolve(root, 'src/styles'), { recursive: true });
writeFileSync(resolve(root, 'src/styles/tokens.css'), app);
writeFileSync(resolve(root, 'src/styles/tokens.reference.css'), reference);
console.log(`tokens: ${tokens.color.tokens.length} colours × ${tokens.color.themes.length} themes, ${tokens.type.groups.reduce((n, g) => n + g.styles.length, 0)} text styles → src/styles/tokens.css`);

// Tailwind's own text sizes (text-xs, text-sm, text-base, text-lg, text-xl…) do nothing here: the theme above replaces
// them with the book's scale, so a class like text-xs silently renders at whatever size it inherits. Stop on any.
const DEAD = /(?<![\w-])text-(xs|sm|base|lg|[2-9]?xl)(?![\w-])/g;
const walk = (dir) => readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(join(dir, e.name)) : /\.(tsx?|css|html)$/.test(e.name) ? [join(dir, e.name)] : []));
const dead = walk(resolve(root, 'src')).flatMap((f) => readFileSync(f, 'utf8').split('\n').flatMap((line, i) =>
  [...line.matchAll(DEAD)].map((m) => `  ${relative(root, f)}:${i + 1}  ${m[0]}`)));
if (dead.length) {
  console.error(`\nThese Tailwind sizes do nothing in Modus Instrument (the token theme replaces them):\n${dead.join('\n')}\n` +
    'Use the book\'s scale: text-caption 12px · text-ui-s 13px · text-body 14px · text-ui-m 15px · text-body-l 16px · text-ui-l 17px · text-statement 20px · text-title 26px. Nothing was built.\n');
  process.exit(1);
}
