// Copies the Modus Create logo geometry from the supplied SVGs into src/components/logo-paths.ts,
// so the Logo component draws the official artwork exactly (never redrawn by hand).
//   npm run logo   — rerun whenever design-system/assets/Logos/ changes
// Sources: MC_Black.svg (wordmark) and MC_Icon_Black.svg (glyph). The White files share the same geometry.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = resolve(root, 'design-system/assets/Logos');

function read(file) {
  const svg = readFileSync(resolve(dir, file), 'utf8');
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  // The artwork's own bounds = the clipPath rect the export wrapped it in (falls back to the viewBox).
  const clip = svg.match(/<clipPath[\s\S]*?<rect[^>]*width="([\d.]+)"[^>]*height="([\d.]+)"/);
  const vb = svg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  const [w, h] = clip ? [clip[1], clip[2]] : [vb[1], vb[2]];
  if (!paths.length) throw new Error(`${file}: no paths found`);
  if (/<(text|image|use)\b/.test(svg)) throw new Error(`${file}: contains live text or images; outline it first`);
  return { viewBox: `0 0 ${w} ${h}`, paths };
}

const wordmark = read('MC_Black.svg');
const glyph = read('MC_Icon_Black.svg');
writeFileSync(
  resolve(root, 'src/components/logo-paths.ts'),
  `/* Generated by scripts/build-logo.mjs from design-system/assets/Logos/. Do not edit by hand. */\n` +
    `export const WORDMARK = ${JSON.stringify(wordmark, null, 2)} as const;\n\n` +
    `export const GLYPH = ${JSON.stringify(glyph, null, 2)} as const;\n`,
);
console.log(`logo: wordmark ${wordmark.paths.length} paths (${wordmark.viewBox}), glyph ${glyph.paths.length} paths (${glyph.viewBox}) → src/components/logo-paths.ts`);
