// The Design System catalogue: one entry per documented component, in display order.
// `npm run ds:build` turns each entry into components/<name>/README.md and preview.html.
// In `preview`, h = React.createElement, M = window.ModusInstrument, S = M.samples.
export const NAMESPACE = 'ModusInstrument';

export const components = [
  {
    name: 'Button', group: 'Actions', height: 190,
    summary: 'Pill button for actions. Filled violet means "you can act here".',
    use: ['Label with a verb and an object: "Export brief", "Book the readout". Never "Submit" or "OK".', 'Use `primary` (filled violet) for each main action a reader can take: in the bar, in a hero, at the end of a chapter. `secondary` for an alternative beside it, `ghost` for low-emphasis actions such as "Copy share link".', 'For an action that goes somewhere, use LinkButton: the same look, a real link.', 'Add `iconEnd={<Icons.ArrowRight />}` when the action moves the viewer forward.'],
    avoid: ['Two primary buttons side by side: one is the main action, the other is secondary.', 'Disabling without saying why. Put the reason in the label ("Disabled · needs data") or next to it.'],
    provides: 'Children (the label), `variant`, `size`, optional `iconEnd`, and any button props (`onClick`, `disabled`, `type`).',
    preview: `h('div', { style: { display: 'flex', flexDirection: 'column', gap: 16 } },
  h('div', { style: { display: 'flex', gap: 12, flexWrap: 'wrap' } },
    h(M.Button, { iconEnd: h(M.Icons.ArrowRight) }, 'Start the walkthrough'),
    h(M.Button, { variant: 'secondary' }, 'Export brief'),
    h(M.Button, { variant: 'ghost', iconEnd: h(M.Icons.ArrowRight) }, 'Copy share link'),
    h(M.Button, { disabled: true }, 'Disabled · needs data')),
  h('div', { style: { display: 'flex', gap: 40, alignItems: 'flex-end', flexWrap: 'wrap' } },
    h('div', { style: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 8 } }, h(M.Button, { size: 'sm' }, 'Share'), h(M.Label, null, 'sm · in a bar')),
    h('div', { style: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 8 } }, h(M.Button, { size: 'md' }, 'Read the brief'), h(M.Label, null, 'md')),
    h('div', { style: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 8 } }, h(M.Button, { size: 'lg' }, 'Book the readout'), h(M.Label, null, 'lg · a chapter\u2019s close'))))`,
  },
  {
    name: 'LinkButton', group: 'Actions', height: 110,
    summary: 'A link drawn as a Button, for actions that go somewhere.',
    use: ['"Plan the workshop", "Read the brief": anything that navigates. It keeps link behaviour (open in a new tab, the address on hover) and shares Button\'s classes, so the two can\'t drift.'],
    avoid: ['A Button with an onClick that changes the address. Use LinkButton.'],
    provides: '`href`, optional `variant`, `size`, `iconEnd`, and any link props.',
    preview: `h('div', { style: { display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center' } },
  h(M.LinkButton, { href: '#', size: 'lg' }, 'Plan the workshop'),
  h(M.LinkButton, { href: '#', variant: 'secondary' }, 'Read the brief'))`,
  },
  {
    name: 'GoLink', group: 'Actions', height: 90,
    summary: 'The second-tier action: words and an arrow, in ink, violet on hover.',
    use: ['The way on: "Next: How the work flows", "Read the brief", "All opportunities" (with `back`).', 'Internal links only. Mark external sources with ↗ instead.'],
    avoid: ['An arrow on every link in a list: make the row the target, or keep one go link per section.'],
    provides: '`href`, children, optional `back` and `current`.',
    preview: `h('div', { style: { display: 'flex', gap: 28, flexWrap: 'wrap' } }, h(M.GoLink, { href: '#' }, 'Next: How the work flows'), h(M.GoLink, { href: '#', back: true }, 'All opportunities'))`,
  },
  {
    name: 'Logo', group: 'Brand', height: 200,
    summary: 'The Modus Create logo, drawn from the official artwork; black on Paper, white on Ink.',
    use: ['Use the wordmark once per page, top-left in the TopBar; the glyph alone below 640px and as a 16px footer sign-off.', 'Size it with a height class (`h-[18px]` for the top bar); the width follows.', 'Pass `label={null}` when a visible product name already names the link.'],
    avoid: ['Recolouring it: it always draws in `color-logo` (black or white, as supplied).', 'Retyping "Modus Create" in Season Sans, or using a PNG, in place of the component.'],
    provides: 'Optional `variant` (`wordmark` | `glyph`), `label` (accessible name, default "Modus Create"), and a height class.',
    preview: `h('div', { style: { display: 'flex', flexDirection: 'column', gap: 24 } },
  h('div', { style: { display: 'flex', gap: 40, alignItems: 'center', flexWrap: 'wrap' } },
    h(M.Logo, { style: { height: 28 } }), h(M.Logo, { variant: 'glyph', style: { height: 36 } })),
  h('div', { style: { display: 'flex', gap: 12, alignItems: 'center', fontSize: 15, fontWeight: 600 } },
    h(M.Logo, { label: null, className: 'h-[18px]' }),
    h('span', { 'aria-hidden': true, style: { width: 1, height: 20, background: 'var(--color-hairline-strong)' } }),
    'Insight Center'))`,
  },
  {
    name: 'Label', group: 'Content', height: 90,
    summary: 'The uppercase annotation voice: IDs, statuses, qualifiers, table heads.',
    use: ['Use one where it says something the heading or the bar doesn\'t: an ID and status ("OPP-01 · Build"), a qualifier ("Illustrative data"), a table head.', 'Use `tone="strong"` on tinted fills and on the violet highlight, where the muted ink would be too light.'],
    avoid: ['A label over every heading, or one that repeats the heading or the nav: a section opens on its claim.', 'Sentences in a label. Labels are two to five words.'],
    provides: 'Children (short text) and optional `tone`.',
    preview: `h('div', { style: { display: 'flex', gap: 28, flexWrap: 'wrap' } },
  h(M.Label, null, 'INS-04 · Intake'), h(M.Label, null, 'Illustrative data'), h(M.Label, { tone: 'strong' }, 'OPP-01 · Build'))`,
  },
  {
    name: 'Tag', group: 'Content', height: 80,
    summary: 'Small uppercase tag for personas, stages and categories.',
    use: ['Tag an insight with the persona and journey stage it belongs to.', 'Reference other items by ID: INS-04, P3, VSM 06.'],
    avoid: ['Using a tag as the only signal of status. Status needs a word and an icon.'],
    provides: 'Children (one or two words).',
    preview: `h('div', { style: { display: 'flex', gap: 8, flexWrap: 'wrap' } }, ['Field adjuster', 'FNOL', 'Policyholder', 'INS-04', 'P3'].map(function (t) { return h(M.Tag, { key: t }, t); }))`,
  },
  {
    name: 'Card', group: 'Content', height: 150,
    summary: 'The panel content sits on: hairline border, 10px radius, no shadow.',
    use: ['Group one piece of content: an insight, a chart, a model.', 'Make panels share borders in a grid (as in the hero) rather than floating them with gaps when the content is one instrument.'],
    avoid: ['Shadows for elevation. Use a surface step (`color-panel` on `color-ground`) and a hairline.', 'A coloured left border. Highlight with `ring-signal` or a tint fill instead.'],
    provides: 'Children, optional `as` (div, article, section, figure) and className for padding.',
    preview: `h(M.Card, { className: 'mi-dots', style: { padding: 32, maxWidth: 520 } }, h('p', { className: 'text-statement', style: { margin: 0 } }, 'Panels sit on the paper ground with a hairline edge. The dot grid goes behind an opening panel only.'))`,
  },
  {
    name: 'EvidenceMeter', group: 'Content', height: 120,
    summary: 'Five bars for how well an insight is supported, always with the word.',
    use: ['1 Anecdote (one source) · 2 Emerging (2–3 agree) · 3 Moderate (a third or more) · 4 Strong (most sources, one method) · 5 Validated (most sources and a second method).', 'Put the evidence in `detail`: "9 of 12 interviews".'],
    avoid: ['Rating evidence by gut feel. The level follows the rule above.'],
    provides: '`level` 1–5 and optional `detail`.',
    preview: `h('div', { style: { display: 'flex', flexDirection: 'column', gap: 10 } }, [1, 2, 3, 4, 5].map(function (n) { return h(M.EvidenceMeter, { key: n, level: n, detail: ['one interview', '3 of 12 interviews', '5 of 12 interviews', '9 of 12 interviews', 'interviews + claims data'][n - 1] }); }))`,
  },
  {
    name: 'StatTile', group: 'Content', height: 200,
    summary: 'A headline number with its label, unit and comparison.',
    use: ['One tile per view: the number the story turns on. A model\'s results, read together, are the exception.', 'State the comparison in words with `delta`; direction shows as an arrow and the good/bad colour.', 'Sizes: `xl` for the hero number, `l` beside a chart, `m` inside a card.'],
    avoid: ['Rows of big numbers. When several numbers relate, draw how they relate instead (a bar to scale, a timeline).', 'A number without a label or a source.'],
    provides: '`label`, `value`, optional `unit`, `note`, `delta`, `size` (m, l, xl), `highlight`.',
    preview: `h(M.StatTile, { size: 'xl', label: 'Lead time · FNOL → payment', value: '22.4', unit: 'days', delta: { text: '9.6 days slower than the peer median', direction: 'down', good: false } })`,
  },
  {
    name: 'Figure', group: 'Content', height: 360,
    summary: 'A titled exhibit with its provenance at the foot; wraps every chart, map and matrix.',
    use: ['The title says what is shown.', 'Put the evidence in the foot: a `tag` ("Illustrative") and a one-line `caption` on the left, the `source` on the right.', 'Number it with `fig` only when the text refers to it ("see Fig 3.1").'],
    avoid: ['A FIG number nothing refers to.', 'A chart without a source line, even when the data is illustrative ("Illustrative · [source]").'],
    provides: '`title`, optional `fig`, `tag`, `caption`, `source`, children (the exhibit).',
    preview: `h(M.Figure, { title: 'Days from first notice to first payment', tag: h(M.Tag, null, 'Illustrative'), caption: 'Median, property claims under $25K', source: '[Benchmark source, year]' }, h(M.BenchmarkBars, { title: '', items: S.benchmark.items, max: 25 }))`,
  },
  {
    name: 'TextField', group: 'Inputs', height: 230,
    summary: 'Labelled input on Base UI Field, with description and error states.',
    use: ['Always label. For a search box with an icon, keep the label and set `hideLabel`.', 'Errors: what is wrong, what to do, and that nothing else was lost.'],
    avoid: ['Placeholder text as the only label.', 'Validating on every keystroke; validate on blur and submit.'],
    provides: '`label`, optional `placeholder`, `description`, `error`, `value`/`defaultValue`, `onValueChange`, `search`.',
    preview: `h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 20 } },
  h(M.TextField, { label: 'Prospect name', placeholder: 'e.g. [Prospect]', description: 'Shown in the top bar and on exports.' }),
  h(M.TextField, { label: 'Workshop date', defaultValue: 'Oct 32', error: 'Enter a real date, like Oct 14. Nothing else was changed.' }),
  h(M.TextField, { label: 'Search insights', hideLabel: true, search: true, placeholder: 'Search insights' }))`,
  },
  {
    name: 'SegmentedTabs', group: 'Inputs', height: 90,
    summary: 'Pill tabs on Base UI Tabs for switching content type; the fill slides to the active tab.',
    use: ['Two to five peers of the same kind: Insights · Maps · Opportunities.', 'Pass `content` per item to let the component own the panels.'],
    avoid: ['Tabs for steps in a sequence; use the ChapterRail.'],
    provides: '`label` (accessible name), `items` [{ value, label, content? }], optional controlled `value`.',
    preview: `h(M.SegmentedTabs, { label: 'Content type', items: [{ value: 'i', label: 'Insights' }, { value: 'm', label: 'Maps' }, { value: 'o', label: 'Opportunities' }] })`,
  },
  {
    name: 'Switch', group: 'Inputs', height: 80,
    summary: 'On/off setting on Base UI Switch, with a visible label.',
    use: ['Settings that apply immediately: Presenter mode, Site motion.'],
    avoid: ['Switches inside forms that need a Save; use a checkbox there.'],
    provides: '`label`, `checked`/`defaultChecked`, `onCheckedChange`.',
    preview: `h('div', { style: { display: 'flex', gap: 28 } }, h(M.Switch, { label: 'Presenter mode', defaultChecked: true }), h(M.Switch, { label: 'Site motion' }))`,
  },
  {
    name: 'Slider', group: 'Inputs', height: 110,
    summary: 'Labelled single-value slider on Base UI Slider, with the value and range ends shown.',
    use: ['Model assumptions people want to drag: claims a year, share eligible.', 'Always pass `format` so the value reads in its unit.'],
    avoid: ['Sliders for values people need to type exactly; use a TextField.'],
    provides: '`label`, `value`, `onValueChange`, `min`, `max`, optional `step`, `format`.',
    preview: `h(function Demo() { var st = React.useState(38); return h('div', { style: { maxWidth: 420 } }, h(M.Slider, { label: 'Share eligible (low severity)', value: st[0], onValueChange: st[1], min: 10, max: 60, format: function (n) { return n + '%'; } })); })`,
  },
  {
    name: 'ThemeToggle', group: 'Inputs', height: 80,
    summary: 'Switches between the Paper and Ink themes by setting data-theme on <html>.',
    use: ['Paper is the default. Offer Ink for big-screen workshop rooms.', 'In a settings panel, where the words help. In a bar, beside a button, use ModeSwitch.', 'Call `setTheme(\'ink\')` to set it from code.'],
    avoid: ['A third theme without adding its values to every colour token.'],
    provides: 'Optional `defaultTheme`.',
    preview: `h(M.ThemeToggle, { defaultTheme: document.documentElement.dataset.theme === 'ink' ? 'ink' : 'paper' })`,
  },
  {
    name: 'ModeSwitch', group: 'Inputs', height: 80,
    summary: 'Light/dark as one on/off switch with a sun and a moon, cut to sit beside a small button.',
    use: ['In a top bar, beside a `sm` Button: same height, edge and focus ring, 12px apart.', 'It is named "Dark mode" for screen readers; on means Ink. Pass `theme` and `onThemeChange` to remember the choice.'],
    avoid: ['Two theme controls on one page.'],
    provides: 'Optional `defaultTheme`, or controlled `theme` with `onThemeChange`.',
    preview: `h('div', { style: { display: 'flex', gap: 12, alignItems: 'center' } }, h(M.ModeSwitch, { defaultTheme: document.documentElement.dataset.theme === 'ink' ? 'ink' : 'paper' }), h(M.Button, { size: 'sm' }, 'Share'))`,
  },
  {
    name: 'AccordionList', group: 'Content', height: 280,
    summary: 'Closed rows that open in place: the name after a violet mark, and a one-line preview of what is inside.',
    use: ['Show the key rows first and keep the rest as closed rows, so the depth is visible without the noise.', 'Write each `preview` as the start of what is inside; it is cut off with an ellipsis.', 'A click anywhere on a closed row opens it; the button carries the state for keyboards and screen readers.'],
    avoid: ['A separate "Show more" button under a list. The rows themselves are the way in.'],
    provides: '`items` [{ id, title, tag?, preview, content }], `idPrefix`.',
    preview: `h('div', { style: { maxWidth: 560 } }, h(M.AccordionList, { idPrefix: 'p', items: [
  { id: 'a', title: 'What goes in and out', preview: 'In: customer and channel signals, product plans. Out: an agreed brief and a forecast.', content: h('p', { className: 'text-body', style: { margin: 0 } }, 'In: customer and channel signals, product plans. Out: an agreed brief and a forecast.') },
  { id: 'b', title: 'Questions to ask', tag: h(M.Tag, null, 'To test'), preview: 'Which assumptions most often change after launch, and who hears first?', content: h('p', { className: 'text-body', style: { margin: 0 } }, 'Which assumptions most often change after launch, and who hears first?') }] }))`,
  },
  {
    name: 'Skeleton', group: 'States', height: 200,
    summary: 'Card-shaped loading placeholder, shown only after about 400ms.',
    use: ['Match the shape of what is loading so nothing jumps when it arrives.'],
    avoid: ['Showing it on fast loads; wait ~400ms first.', 'Flashing it on refetch; keep the old content at reduced opacity.'],
    provides: 'Optional `lines`.',
    preview: `h('div', { style: { maxWidth: 360 } }, h(M.Skeleton))`,
  },
  {
    name: 'EmptyState', group: 'States', height: 280,
    summary: 'What belongs here, why it is empty, and the next action.',
    use: ['Name the filter or condition that emptied the view and offer a way out.'],
    avoid: ['A blank area, or "No data".'],
    provides: '`title`, `description`, optional `actions` (Buttons).',
    preview: `h('div', { style: { maxWidth: 380 } }, h(M.EmptyState, { title: 'No insights match these filters.', description: 'Nothing is tagged Field adjuster in the Payment stage yet. Try another stage, or clear the filters.', actions: [h(M.Button, { key: 1, size: 'sm' }, 'Clear filters'), h(M.Button, { key: 2, size: 'sm', variant: 'secondary' }, 'Browse all 24')] }))`,
  },
  {
    name: 'ErrorState', group: 'States', height: 300,
    summary: 'What happened, why, what to do, and whether anything was lost.',
    use: ['Keep the user’s input and say so.', 'Offer a retry and a degraded path ("Show without quotes").'],
    avoid: ['Apologies and vague copy ("Something went wrong").', 'Dead ends with no action.'],
    provides: '`what`, `detail`, optional `title` and `actions`.',
    preview: `h('div', { style: { maxWidth: 380 } }, h(M.ErrorState, { what: 'Couldn’t load interview excerpts', title: 'The quotes for these insights didn’t arrive.', detail: 'The research library timed out. Your filters and selections are kept — nothing was lost.', actions: [h(M.Button, { key: 1, size: 'sm' }, 'Try again'), h(M.Button, { key: 2, size: 'sm', variant: 'secondary' }, 'Show without quotes')] }))`,
  },
  {
    name: 'InsightCard', group: 'Insight Center', height: 380,
    summary: 'A research insight: the claim, its evidence, the voice behind it and where it leads.',
    use: ['Write the statement as one sentence that makes a claim.', 'Quote a real participant with role, never a name.', 'Set `selected` when the insight is in the brief.'],
    avoid: ['Statements that describe a topic ("Intake process") instead of a finding.', 'Invented quotes.'],
    provides: '`insight` { id, stage, evidence 1–5, evidenceDetail, statement, quote?, quoteBy?, tags?, linkLabel?, href? }, optional `selected`, `selectedNote`.',
    preview: `h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 20 } }, h(M.InsightCard, { insight: S.insights[0] }), h(M.InsightCard, { insight: S.insights[2], selected: true, selectedNote: 'Added to the brief · slide 4' }))`,
  },
  {
    name: 'OpportunityCard', group: 'Insight Center', height: 520,
    summary: 'An opportunity in brief: today and with us, the value, the confidence and the time to value.',
    use: ['`kind="build"` for new technology built with us; `kind="evolve"` for AI-assisted ways of working.', 'Three metrics, each with its unit in the label. Mark unvalidated numbers ("to validate").'],
    avoid: ['Value claims without the model behind them; link to the vignette.'],
    provides: '`opportunity` { id, kind, title, today, future, metrics[3], confidence 1–3, timeToValue, insights?, href? }.',
    preview: `h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 20 } }, h(M.OpportunityCard, { opportunity: S.opportunities[0] }), h(M.OpportunityCard, { opportunity: S.opportunities[1] }))`,
  },
  {
    name: 'TopBar', group: 'Navigation', height: 110, width: 1280,
    summary: 'Product bar: the Modus Create logo and product name, who the brief is for, section links and actions.',
    use: ['Say who it is for in `context` when the product name doesn\'t already.', 'Mark the whole site with a `badge` after the name (an "Example" or "Draft" tag), and repeat its word in `brandLabel`.', 'Put Ask, ModeSwitch and Share in `actions`.', 'Set `product` for products other than Insight Center; on phones a long name wraps onto two lines.'],
    avoid: ['More than six section links.', 'A second logo elsewhere in the bar.'],
    provides: 'Optional `product` (default "Insight Center"), `badge`, `brandLabel`, `context`, `sections` [{ label, href?, current? }], `actions`.',
    preview: `h(M.TopBar, { context: 'Prepared for [Prospect] · Commercial claims POV', sections: [{ label: 'Brief', current: true }, { label: 'Insights' }, { label: 'Maps' }, { label: 'Opportunities' }], actions: [h(M.AskPalette, { key: 1, items: S.askItems, answer: S.askAnswer }), h(M.Button, { key: 2, size: 'sm' }, 'Share')] })`,
  },
  {
    name: 'ChapterRail', group: 'Navigation', height: 520,
    summary: 'The walkthrough’s chapter index: what has been read and where you are. Each row fills on hover.',
    use: ['Keep it sticky beside long-scroll chapters.', 'Numbered because the chapters are a real sequence.'],
    avoid: ['Using it for unordered sections; use the TopBar, or SectionRail for a page people dip into.'],
    provides: '`chapters` [{ n, title, meta?, status (done, current, next), progress?, href? }].',
    preview: `h('div', { style: { maxWidth: 320 } }, h(M.ChapterRail, { chapters: S.chapters }))`,
  },
  {
    name: 'SectionRail', group: 'Navigation', height: 320,
    summary: 'The sticky index beside a long page people dip into: a line of dots, the current one in violet.',
    use: ['From 1024px, at `layout-rail` (280px), beside a page of several sections.', 'Feed `current` from where the reader is, so the violet dot follows them.'],
    avoid: ['Read · Reading now · Up next words: they suit a guided walkthrough (ChapterRail), not a page people dip into.'],
    provides: 'Optional `label` (default "On this page"), `items` [{ id, name, href }], `current` (index).',
    preview: `h('div', { style: { maxWidth: 280 } }, h(M.SectionRail, { items: [{ id: 'a', name: 'The offer', href: '#' }, { id: 'b', name: 'What you get', href: '#' }, { id: 'c', name: 'How we work together', href: '#' }, { id: 'd', name: 'Plan the workshop', href: '#' }], current: 1 }))`,
  },
  {
    name: 'ChapterHeader', group: 'Navigation', height: 220,
    summary: 'A chapter\'s opening: one plain claim at display-m, then one sentence of intro.',
    use: ['Write the claim as the chapter\'s point, in one tone ("Much of the work happens between teams and partners.").', 'One sentence of intro, then the exhibit.'],
    avoid: ['An eyebrow repeating the bar or the rail.', 'A grey second line: two tones belong to the page\'s point of view only.', 'A title that leads with a count ("Six opportunities to explore").'],
    provides: '`claim`, optional `intro` and children.',
    preview: `h(M.ChapterHeader, { claim: 'Investigation waits eight days for six hours of work.', intro: 'Each step\u2019s waiting time is drawn above the line and its work below it, to scale.' })`,
  },
  {
    name: 'ChapterClose', group: 'Navigation', height: 200,
    summary: 'The end of a chapter: its own question for the reader\'s team, the main action and the way on.',
    use: ['Write the question for this chapter ("Where does work most often stall between your teams and partners?").', 'The main action is a LinkButton; the way on a GoLink.'],
    avoid: ['The same closing band on every page: a hairline above, no band, no dots, no label.'],
    provides: '`question`, optional `action`, `next` and `label` (the region\'s name).',
    preview: `h(M.ChapterClose, { question: 'Which of these should the workshop test first?', action: h(M.LinkButton, { href: '#', size: 'lg' }, 'Book the readout'), next: h(M.GoLink, { href: '#' }, 'Next: How you compare') })`,
  },
  {
    name: 'AskPalette', group: 'Navigation', height: 490,
    summary: 'Ask or jump to anything; AI answers are labelled unreviewed until a person checks them. Opens with ⌘K.',
    use: ['Give every answer its `provenance` and `sources`.', 'Set `reviewed: true` only after someone on the team has checked the answer.'],
    avoid: ['Presenting a drafted answer as verified.'],
    provides: '`items` [{ id, title, where, group }], optional `answer`, `defaultQuery`, `onSelect`, `inline`.',
    preview: `h(M.AskPalette, { inline: true, items: S.askItems, answer: S.askAnswer, defaultQuery: 'approval' })`,
  },
  {
    name: 'ValueStream', group: 'Maps and data', height: 580, width: 1100,
    summary: 'Value stream map: process boxes, the wait-and-work ladder, and the lead time drawn to scale.',
    use: ['Mark exactly one step `bottleneck`; it becomes the violet bar and box.', 'Give process time as people say it ("6 h") and in working days for the scale bar.'],
    avoid: ['More than nine steps; group them.'],
    provides: '`steps` [{ name, owner, systems?, processTime, processDays, waitDays, bottleneck? }].',
    preview: `h(M.ValueStream, { steps: S.valueStream })`,
  },
  {
    name: 'ServiceBlueprint', group: 'Maps and data', height: 650, width: 1100,
    summary: 'Service blueprint as a lane by phase grid, with lines of interaction and visibility.',
    use: ['Four lanes: customer actions, frontstage, backstage, support systems.', 'Number pain points by impact (P1 is worst) and mark moments that matter.'],
    avoid: ['More than one pain per cell.'],
    provides: '`phases` [{ name, time? }], `lanes` [{ name, description, cells [{ text, kind?, badge? }] }], optional `lines`.',
    preview: `h(M.ServiceBlueprint, { phases: S.blueprintPhases, lanes: S.blueprintLanes })`,
  },
  {
    name: 'CapabilityMatrix', group: 'Maps and data', height: 520, width: 900,
    summary: 'Capabilities by players, scored 0–4 with Harvey balls, in a real table.',
    use: ['Highlight the prospect column. Anonymise peers.'],
    avoid: ['Colour-coded scores; the ball shape carries the value.'],
    provides: '`caption`, `players`, `rows` [{ capability, scores }], optional `highlight` index.',
    preview: `h(M.CapabilityMatrix, { caption: S.matrix.caption, players: S.matrix.players, rows: S.matrix.rows })`,
  },
  {
    name: 'HarveyBall', group: 'Maps and data', height: 70,
    summary: 'A 0–4 score as a quarter-filled circle, announced by name.',
    use: ['Inside matrices and comparison tables.'],
    avoid: ['Scores above 4 or fractional scores.'],
    provides: '`score` 0–4, optional `size`.',
    preview: `h('div', { style: { display: 'flex', gap: 20 } }, [0, 1, 2, 3, 4].map(function (n) { return h(M.HarveyBall, { key: n, score: n, size: 24 }); }))`,
  },
  {
    name: 'BenchmarkBars', group: 'Maps and data', height: 290,
    summary: 'One measure across a few comparators: the story bar in violet, the rest neutral, every value labelled.',
    use: ['Two to six bars. Highlight the prospect.'],
    avoid: ['A second axis or a second measure; make a second chart.'],
    provides: '`title`, `items` [{ label, value, highlight? }], optional `source`, `unit`, `max`.',
    preview: `h('div', { style: { maxWidth: 560 } }, h(M.BenchmarkBars, { title: S.benchmark.title, source: S.benchmark.source, items: S.benchmark.items, max: 25 }))`,
  },
  {
    name: 'RoiModel', group: 'Maps and data', height: 760, width: 1100,
    summary: 'A live ROI model: drag the assumptions, watch payback move; the assumptions are always on screen.',
    use: ['Open with the workshop values in `defaults` and let people reset to them.', 'Keep the formula note visible; replace inputs with validated client data before sharing.'],
    avoid: ['Showing an ROI without its assumptions.'],
    provides: '`defaults` { claimsPerYear, eligiblePct, autoPct, savedPerClaim, buildCost, runCostPerYear, buildMonths?, rampMonths?, horizonMonths? }. The maths is `computeRoi` in the bundle.',
    preview: `h(M.RoiModel, { defaults: S.roiDefaults })`,
  },
];
